eval({"rank":"-text_relevance","match-expr":"(label \'Love\')","hits":{"found":100,"start":0,"hit":[
    {"id":"tt0407269","data":{"actor":["Boyd, Tom","Carmichael, Harriet","Christian, David","Hensey, Julian","Hewitt, Jennifer Love","Miles, Kate","Mistry, Jimi","O\'Flaherty, Tracy","Rayner, Elise","Roche, Theresa","Scott, Dougray","Valeydon-Pillay, Frances","Waters, Freddie"],"director":["Hay, John"],"text_relevance":["430"],"title":["The Truth About Love"],"year":["2005"]}},
    {"id":"tt0385705","data":{"actor":["Denham, Tony","Dyer, Danny","Farrell, Frida","Foreman, Jamie","Harper, Frank","Hassan, Tamer","Howard, Philip","Humby, Stephen","Junkin, John","Karne, Sid","Kelly, Danny","Lawson, Steven","Love, Samantha","Manookian, Roland","Maskell, Neil","McNab, Calum","Osgood, Peter","Parfitt, Andy","Sneller, Robin","Sutton, Dudley"],"director":["Love, Nick"],"text_relevance":["428"],"title":["The Football Factory"],"year":["2004"]}},
    {"id":"tt1844777","data":{"actor":["Love, Courtney","Richardson, Sy","Rude, Dick","Strummer, Joe"],"director":["Cox, Alex"],"text_relevance":["255"],"title":["Straight to Hell Returns"],"year":["2010"]}},
    {"id":"tt0823188","data":{"actor":["Fallon, Mike","Longino, Eleese","Love, Jillian","Mosley, Michelle","Richardson, Cory","Shelburne, Brian","Tyler, Matthew"],"director":["Lawrence, Colton"],"text_relevance":["252"],"title":["The Sex Movie"],"year":["2006"]}},
    {"id":"tt0382189","data":{"actor":["Andrews, Dean","Antony-Barber, Paul","Blunt, Emily","Byrne, Michelle","Considine, Paddy","Edwards, Lynette","Press, Natalie","Sumner, Kathryn"],"director":["Pawlikowski, Pawel"],"text_relevance":["249"],"title":["My Summer of Love"],"year":["2004"]}},
    {"id":"tt0280380","data":{"actor":["Bacon, Kevin","Chalk, Garry","Fanning, Dakota","Koby, Matt","Love, Courtney","Markell, Jodie","Rankin, Steve","Theron, Charlize","Townsend, Stuart","Vince, Pruitt Taylor"],"director":["Mandoki, Luis"],"text_relevance":["249"],"title":["Trapped"],"year":["2002"]}},
    {"id":"tt0068468","data":{"actor":["Birch, Jack","Byron, John","Connors, Carol","Harrison, Bill","Love, William","Phillips, Bob","Reems, Harry","Sharp, Dolly","Street, Ted","Wertheim, Ron"],"director":["Damiano, Gerard"],"text_relevance":["249"],"title":["Deep Throat"],"year":["1972"]}},
    {"id":"tt0116743","data":{"actor":["Andrews, Naveen","Bhansali, Surabhi","Choudhury, Sarita","Dhup, Garima","Padamsee, Pearl","Rao, Arundhati","Rekha","Tikaram, Ramon","Tyabji, Khalid","Varma, Indira"],"director":["Nair, Mira"],"text_relevance":["248"],"title":["Kama Sutra: A Tale of Love"],"year":["1996"]}},
    {"id":"tt1032815","data":{"actor":["Avgeropoulos, Marie","Carpenter, Jack","Emerson, Josh","Keeso, Jared","London, Lauren","Panettiere, Hayden","Penny, Brendan","Roberts, Shawn","Rust, Paul","Storm, Lauren"],"director":["Columbus, Chris"],"text_relevance":["248"],"title":["I Love You, Beth Cooper"],"year":["2009"]}},
    {"id":"tt0112688","data":{"actor":["Byrd, Thomas Jefferson","David, Keith","Douglas, Brother Eden","Fingaz, Sticky","Keitel, Harvey","Lindo, Delroy","Love, Peewee","Phifer, Mekhi","Taylor, Regina","Turturro, John","Washington, Isaiah"],"director":["Lee, Spike"],"text_relevance":["248"],"title":["Clockers"],"year":["1995"]}}
]},"facets":{"genre":{"constraints":[
    {"value":"Comedy","count":56},
    {"value":"Drama","count":52},
    {"value":"Romance","count":50},
    {"value":"Thriller","count":18},
    {"value":"Crime","count":16},
    {"value":"Action","count":11},
    {"value":"Sport","count":8},
    {"value":"Fantasy","count":6},
    {"value":"Mystery","count":6},
    {"value":"Biography","count":5},
    {"value":"Adventure","count":4},
    {"value":"Family","count":4},
    {"value":"Horror","count":4},
    {"value":"Music","count":3},
    {"value":"Musical","count":2},
    {"value":"Western","count":2},
    {"value":"Adult","count":1},
    {"value":"Animation","count":1},
    {"value":"History","count":1},
    {"value":"Sci-Fi","count":1},
    {"value":"War","count":1}
]}},"info":{"rid":"8a0620f6c72ff3e7e6984cfa7dfcb54478878494e7cd6e3807d7731c7b3216c5aed11aafef97d402","time-ms":3,"cpu-time-ms":0}})
